--db 변경후 같이 변경 부탁!
drop table EMPLOYEE;
DROP SEQUENCE POSITIONSEQ;

CREATE TABLE EMPLOYEE(
    EMPLOYEEID VARCHAR2(100) PRIMARY KEY,
    POSITIONSEQ NUMBER,
    PASSWORD VARCHAR2(100) NOT NULL,
    NAME VARCHAR(10) NOT NULL,
    HIREDATE DATE DEFAULT SYSDATE,
    BIRTHDATE DATE ,
    PHONE VARCHAR2(100),
    ADDRESS VARCHAR2(100),
    FIREDATE DATE DEFAULT null,
    GENDER VARCHAR2(6) NOT NULL

);

CREATE SEQUENCE POSITIONSEQ;

COMMIT;